// Package artifacttest is test support for the query layer: the fixture
// catalogues and the artifact builders that pkg/query's tests, internal/serve's
// tests and pkg/query/querytest (the public face, for downstream consumers) all
// build their artifacts from, and the HTTP helpers the first two serve them
// through (http.go). ONE home, because a fixture that differs between
// the suite that tests the query layer and the suite that tests the server built
// on it is the one kind of drift neither suite can catch.
//
// Every artifact is built with the real builder (internal/build) at a FIXED build
// time, so a fixture artifact is deterministic: two builds of one catalogue are
// byte-identical, and an ETag or a golden that names built_at is stable.
package artifacttest

import (
	"database/sql"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	_ "modernc.org/sqlite"

	"github.com/kodestar/audiosilo-meta/internal/build"
	"github.com/kodestar/audiosilo-meta/pkg/model"
)

// BuiltAtRFC3339 is the build time every fixture artifact is stamped with, as
// the artifact's meta(built_at) spells it.
const BuiltAtRFC3339 = "2026-07-11T00:00:00Z"

// BuiltAt is BuiltAtRFC3339 as a time, which is what the builder takes.
var BuiltAt = func() time.Time {
	t, err := time.Parse(time.RFC3339, BuiltAtRFC3339)
	if err != nil {
		panic(err)
	}
	return t
}()

// The facts Fixture is built from, named once so pkg/query/querytest's public
// constants are these values rather than a second copy of them.
const (
	// HailMary is the fully fleshed work: one recording (HailMaryRecording) with
	// a cover, chapters, the ASIN HailMaryASIN and the whole community layer,
	// and a retired slug (HailMaryRetired) that redirects to it.
	HailMary          = "project-hail-mary"
	HailMaryRecording = "ray-porter-2021"
	HailMaryASIN      = "B08G9PRS1K"
	HailMaryRetired   = "project-hail-mary-audiobook"
	// WayOfKings is the work with an ISBN (WayOfKingsISBN on its recording
	// WayOfKingsRecording) and two narrators, and the first of Stormlight.
	WayOfKings          = "the-way-of-kings"
	WayOfKingsRecording = "kramer-reading-2010"
	WayOfKingsISBN      = "9781427209269"
	// Stormlight is the series holding works at positions "1", "2" and "10".
	Stormlight = "the-stormlight-archive"
)

// Build writes cat's artifact into a fresh temporary directory and returns its
// path.
func Build(tb testing.TB, cat *model.Catalog) string {
	tb.Helper()
	out := filepath.Join(tb.TempDir(), "meta.sqlite")
	BuildAt(tb, cat, out)
	return out
}

// BuildAt writes cat's artifact at path.
func BuildAt(tb testing.TB, cat *model.Catalog, path string) {
	tb.Helper()
	if err := build.Build(cat, path, BuiltAt); err != nil {
		tb.Fatal(err)
	}
}

// Golden compares a rendered document with the golden file at path, or rewrites
// that file when update is set (each package's -update-golden flag). Every golden
// test goes through it, so a deliberate rendering change is regenerated by one
// flag and shows up as a reviewable diff of the document itself.
func Golden(tb testing.TB, path string, got []byte, update bool) {
	tb.Helper()
	if update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			tb.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		tb.Fatalf("read %s: %v (regenerate with -update-golden)", path, err)
	}
	if string(got) != string(want) {
		tb.Logf("rendered:\n%s", got)
		tb.Errorf("rendered document differs from %s (regenerate with -update-golden)", path)
	}
}

// Downgraded builds cat's artifact and rolls it back to an older one by
// dropping dropTables and stamping version: the rollback itself, without a server
// around it, so a test that asks the QUERY LAYER how it degrades (rather than what
// a route answers) opens this path directly.
//
// The CATALOGUE is a parameter because the version gates are not all visible in
// one fixture: the guide families need a catalogue whose two recap tables name
// DIFFERENT works, which the shared fixture (both sidecars on one work) cannot
// show. Most callers pass Fixture().
func Downgraded(tb testing.TB, cat *model.Catalog, version int, dropTables ...string) string {
	tb.Helper()
	stmts := make([]string, len(dropTables))
	for i, tbl := range dropTables {
		stmts[i] = "DROP TABLE " + tbl
	}
	return Altered(tb, cat, version, stmts...)
}

// Altered builds cat's artifact, runs stmts against it and stamps
// meta(schema_version) to version: the general form of Downgraded, for a shape a
// dropped table cannot express (dropped columns and indexes) or an artifact that
// CLAIMS a version it does not have.
func Altered(tb testing.TB, cat *model.Catalog, version int, stmts ...string) string {
	tb.Helper()
	dbPath := Build(tb, cat)

	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		tb.Fatal(err)
	}
	for _, stmt := range stmts {
		if _, err := db.Exec(stmt); err != nil {
			tb.Fatalf("%s: %v", stmt, err)
		}
	}
	if _, err := db.Exec("UPDATE meta SET value=? WHERE key='schema_version'", strconv.Itoa(version)); err != nil {
		tb.Fatal(err)
	}
	if err := db.Close(); err != nil {
		tb.Fatal(err)
	}
	return dbPath
}

// Fixture is a small but representative dataset: two fully-fleshed works
// (one with a cover + chapters + ASIN, one with an ISBN + dual narrators) plus
// two thin works that only exist to exercise numeric series ordering.
func Fixture() *model.Catalog {
	andy := &model.Person{ID: "andy-weir", Name: "Andy Weir", License: "CC0-1.0"}
	porter := &model.Person{ID: "ray-porter", Name: "Ray Porter", License: "CC0-1.0"}
	sando := &model.Person{ID: "brandon-sanderson", Name: "Brandon Sanderson", License: "CC0-1.0"}
	kramer := &model.Person{ID: "michael-kramer", Name: "Michael Kramer", License: "CC0-1.0"}
	reading := &model.Person{ID: "kate-reading", Name: "Kate Reading", License: "CC0-1.0"}

	phm := &model.Work{
		ID: HailMary, Title: "Project Hail Mary", Language: "en",
		Authors: []string{"andy-weir"}, License: "CC0-1.0",
		Genres: []string{"hard-science-fiction", "science-fiction"},
		// The one fixture work with an added_at, so the "latest" ordering has
		// something to put first. It sits on the record now: the builder takes
		// no date map.
		AddedAt: "2026-07-10T00:00:00Z",
		Recordings: []*model.Recording{{
			ID: HailMaryRecording, Work: HailMary, Language: "en",
			RuntimeMin: 970, Publisher: "Audible Studios", ReleaseDate: "2021-05-04",
			CoverURL: "https://example.test/phm.jpg", License: "CC0-1.0",
			Narrators: []string{"ray-porter"},
			ASIN:      []model.ASIN{{Region: "us", ASIN: HailMaryASIN}},
			Chapters: []model.Chapter{
				{Title: "Opening Credits", StartMS: 0, LengthMS: 5000},
				{Title: "Chapter 1", StartMS: 5000, LengthMS: 600000},
				{Title: "Chapter 2", StartMS: 605000, LengthMS: 600000},
			},
		}},
	}
	wok := &model.Work{
		ID: WayOfKings, Title: "The Way of Kings", Language: "en",
		Authors: []string{"brandon-sanderson"}, License: "CC0-1.0",
		Recordings: []*model.Recording{{
			ID: WayOfKingsRecording, Work: WayOfKings, Language: "en",
			Narrators: []string{"michael-kramer", "kate-reading"}, License: "CC0-1.0",
			ISBN: []model.ISBNRef{{ISBN: WayOfKingsISBN}},
		}},
	}
	wor := &model.Work{
		ID: "words-of-radiance", Title: "Words of Radiance", Language: "en",
		Authors: []string{"brandon-sanderson"}, License: "CC0-1.0",
	}
	edge := &model.Work{
		ID: "edgedancer", Title: "Edgedancer", Language: "en",
		Authors: []string{"brandon-sanderson"}, License: "CC0-1.0",
	}

	series := &model.Series{
		ID: Stormlight, Name: "The Stormlight Archive", License: "CC0-1.0",
		Authors: []string{"brandon-sanderson"},
		Works: []model.SeriesWork{
			{Work: WayOfKings, Position: "1"},
			{Work: "words-of-radiance", Position: "2"},
			{Work: "edgedancer", Position: "10"}, // "10" < "2" as a string; must sort last numerically
		},
	}
	chars := &model.Characters{
		Work: HailMary, License: "CC-BY-SA-4.0",
		Sources: []model.Source{{Type: "community"}},
		Characters: []model.Character{
			{
				ID: "ryland-grace", Name: "Ryland Grace", Role: "protagonist",
				Aliases: []string{"Dr. Grace"}, Reveal: model.Position{Chapter: 1},
				Description: "A science teacher who wakes aboard the ship with amnesia.",
				Xref:        &model.CharacterXref{Wikidata: "Q110001"},
			},
			{ID: "rocky", Name: "Rocky", Role: "supporting", Reveal: model.Position{Chapter: 8}},
		},
	}
	recaps := &model.Recaps{
		Work: HailMary, License: "CC-BY-SA-4.0",
		Sources: []model.Source{{Type: "community"}},
		InShort: "A lone amnesiac wakes aboard a ship, befriends an alien, and saves both worlds.",
		Ending:  "Grace stays on Erid while the cure flies home.",
		Recaps: []model.Recap{
			{Through: model.Position{Chapter: 9}, Scope: "book", Text: "First contact is made."},
			{Through: model.Position{Chapter: 2}, Scope: "book", Text: "Grace wakes with amnesia."},
		},
	}
	// The spoiler-free description: past the schema's 200-character floor, and
	// deliberately saying nothing the recap above says - it is what the meta tag,
	// the fact sheet, the JSON-LD and the ABS facade all read.
	desc := &model.Description{
		Work: HailMary, License: "CC-BY-SA-4.0",
		Sources: []model.Source{{Type: "community"}},
		Text: "A junior-high science teacher wakes alone aboard a ship he does not remember boarding, " +
			"with two dead crewmates and no idea how far from home he is. What comes back to him arrives " +
			"in pieces, and none of it is good news for anybody still on Earth.",
	}
	return &model.Catalog{
		Works:        []*model.Work{phm, wok, wor, edge},
		People:       []*model.Person{andy, porter, sando, kramer, reading},
		Series:       []*model.Series{series},
		Characters:   []*model.Characters{chars},
		Recaps:       []*model.Recaps{recaps},
		Descriptions: []*model.Description{desc},
		// One retired slug per namespace, the shape a duplicate merge leaves
		// behind: the loser's slug still resolves, at the survivor.
		Redirects: model.Redirects{
			model.RedirectWorks:  {HailMaryRetired: HailMary},
			model.RedirectPeople: {"andy-weir-author": "andy-weir"},
			model.RedirectSeries: {"stormlight-archive": Stormlight},
		},
	}
}

// Languages is a small franchise carrying every schema_version 7 fact.
//
//   - "The Saga" (the-saga) is the PRIMARY ordering, in publication order, with
//     two VARIANT orderings of it: saga-chronological, whose id sorts BEFORE the
//     primary's (the case firstSeriesByWork's primary preference exists for), and
//     the-saga-recommended, whose id sorts after it.
//   - book-one sits in all three, so a card, a work page's series[0] and its
//     JSON-LD isPartOf have three series to choose from.
//   - buch-eins and livre-un translate book-one; sammelband is a translated
//     omnibus of book-one AND book-two; die-saga translates the-saga.
func Languages() *model.Catalog {
	jane := &model.Person{ID: "jane-doe", Name: "Jane Doe", License: "CC0-1.0"}
	work := func(id, title, lang string, of ...string) *model.Work {
		return &model.Work{
			ID: id, Title: title, Language: lang, Authors: []string{"jane-doe"},
			License: "CC0-1.0", TranslationOf: of,
		}
	}
	members := func(pairs ...string) []model.SeriesWork {
		var out []model.SeriesWork
		for _, p := range pairs {
			w, pos, _ := strings.Cut(p, "@")
			out = append(out, model.SeriesWork{Work: w, Position: pos})
		}
		return out
	}
	return &model.Catalog{
		People: []*model.Person{jane},
		Works: []*model.Work{
			work("book-one", "Book One", "en"),
			work("book-two", "Book Two", "en"),
			work("the-prequel", "The Prequel", "en"),
			work("buch-eins", "Buch Eins", "de", "book-one"),
			work("livre-un", "Livre Un", "fr", "book-one"),
			work("sammelband", "Sammelband", "de", "book-one", "book-two"),
		},
		Series: []*model.Series{
			{
				ID: "the-saga", Name: "The Saga", License: "CC0-1.0", Authors: []string{"jane-doe"},
				Works: members("book-one@1", "book-two@2"), Ordering: model.OrderingPublication,
			},
			{
				ID: "saga-chronological", Name: "The Saga (Chronological Order)", License: "CC0-1.0",
				Works:    members("the-prequel@1", "book-one@2", "book-two@3"),
				Ordering: model.OrderingChronological, OrderingOf: "the-saga",
			},
			{
				ID: "the-saga-recommended", Name: "The Saga (Recommended Order)", License: "CC0-1.0",
				Works:    members("book-one@1", "the-prequel@2", "book-two@3"),
				Ordering: model.OrderingRecommended, OrderingOf: "the-saga",
			},
			{
				ID: "die-saga", Name: "Die Saga", License: "CC0-1.0",
				Works: members("buch-eins@1", "sammelband@2"), TranslationOf: []string{"the-saga"},
			},
		},
	}
}
