package serve

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"
	"unicode/utf8"

	"github.com/kodestar/audiosilo-meta/pkg/model"
)

var watchFeedNow = time.Date(2026, 10, 20, 15, 30, 0, 0, time.UTC)

func watchFeedCatalog() *model.Catalog {
	cat := fixtureCatalog()
	for _, work := range cat.Works {
		switch work.ID {
		case "the-way-of-kings":
			work.Recordings[0].ReleaseDate = "2026-10-20"
		case "words-of-radiance":
			work.Recordings = []*model.Recording{{
				ID: "future-recording", Work: work.ID, Language: "en",
				ReleaseDate: "2026-11", License: "CC0-1.0",
			}}
		case "edgedancer":
			work.AddedAt = "2026-10-19T12:00:00Z"
		}
	}
	return cat
}

func newWatchFeedServer(t *testing.T, cat *model.Catalog) (*Server, *httptest.Server) {
	t.Helper()
	srv, err := New(Config{
		DBPath:    buildFixtureDB(t, cat),
		SiteURL:   testSiteURL,
		swapGrace: time.Minute,
		now:       func() time.Time { return watchFeedNow },
	})
	if err != nil {
		t.Fatal(err)
	}
	ts := httptest.NewServer(srv.Handler())
	t.Cleanup(ts.Close)
	return srv, ts
}

func watchFeedResponse(t *testing.T, ts *httptest.Server, path string) (*http.Response, []byte) {
	t.Helper()
	resp, err := http.Get(ts.URL + path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatal(err)
	}
	return resp, body
}

func TestWatchFeedGoldens(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	for _, tc := range []struct {
		name        string
		path        string
		contentType string
	}{
		{"atom", "/api/v1/watch/feed.atom?s=the-stormlight-archive,not-here", "application/atom+xml; charset=utf-8"},
		{"json", "/api/v1/watch/feed.json?s=the-stormlight-archive,not-here", "application/feed+json; charset=utf-8"},
		{"ics", "/api/v1/watch/releases.ics?s=the-stormlight-archive,not-here", "text/calendar; charset=utf-8"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resp, got := watchFeedResponse(t, ts, tc.path)
			if resp.StatusCode != http.StatusOK {
				t.Fatalf("status = %d, body %s", resp.StatusCode, got)
			}
			if ct := resp.Header.Get("Content-Type"); ct != tc.contentType {
				t.Errorf("Content-Type = %q, want %q", ct, tc.contentType)
			}
			if got := resp.Header.Get("Cache-Control"); got != watchFeedMaxAge {
				t.Errorf("Cache-Control = %q", got)
			}
			if got := resp.Header.Get("Access-Control-Allow-Origin"); got != "*" {
				t.Errorf("Access-Control-Allow-Origin = %q", got)
			}
			golden := filepath.Join("testdata", "golden", "watch-feed."+tc.name)
			// Regenerated by the same -update-golden flag as the entity pages
			// (html_test.go), for the same reason: a deliberate change to the
			// rendering shows up as a reviewable diff of the document itself.
			if *updateGolden {
				if err := os.WriteFile(golden, got, 0o644); err != nil {
					t.Fatal(err)
				}
				return
			}
			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("read %s: %v (regenerate with -update-golden)\nrendered body:\n%s", golden, err, got)
			}
			if string(got) != string(want) {
				t.Errorf("rendered feed differs from %s (regenerate with -update-golden)\nrendered body:\n%s", golden, got)
			}
		})
	}
}

func TestWatchItemWindowAndDatePrecision(t *testing.T) {
	now := time.Date(2026, 9, 21, 15, 0, 0, 0, time.UTC)
	card := func(id, release, added string) *workCard {
		var addedAt *string
		if added != "" {
			addedAt = &added
		}
		return &workCard{ID: id, Title: id, ReleaseDate: release, AddedAt: addedAt}
	}
	cases := []struct {
		name    string
		card    *workCard
		keep    bool
		state   string
		updated string
	}{
		{"year uses first day", card("year", "2026", ""), false, "", ""},
		{"future month uses first day", card("month", "2026-10", ""), true, "preorder", "2026-10-01T00:00:00Z"},
		{"today is released", card("today", "2026-09-21", ""), true, "released", "2026-09-21T00:00:00Z"},
		{"release boundary included", card("boundary", "2026-06-23", ""), true, "released", "2026-06-23T00:00:00Z"},
		{"release before boundary excluded", card("old", "2026-06-22", ""), false, "", ""},
		{"unknown exact boundary included", card("unknown", "", "2026-06-23T15:00:00Z"), true, "date unknown", "2026-06-23T15:00:00Z"},
		{"unknown before boundary excluded", card("older-unknown", "", "2026-06-23T14:59:59Z"), false, "", ""},
		{"unknown date boundary included", card("unknown-date", "", "2026-06-23"), true, "date unknown", "2026-06-23T00:00:00Z"},
		// `date_flex` is a PATTERN, so a calendar-invalid value is schema-valid
		// and reaches the artifact. It must not delete the work from the feed:
		// the site renders it and lists the entry, so the feed falls through to
		// the added_at rule rather than disagreeing.
		{"calendar-invalid date falls through to added_at", card("bad-month", "2026-13", "2026-09-20"), true, "date unknown", "2026-09-20T00:00:00Z"},
		{"calendar-invalid date with no added_at is not news", card("bad-day", "2026-02-30", ""), false, "", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			item, ok := watchItem("Series", seriesEntry{Position: "1", Work: tc.card}, 90, now, testSiteURL)
			if ok != tc.keep {
				t.Fatalf("keep = %v, want %v", ok, tc.keep)
			}
			if !ok {
				return
			}
			if item.state != tc.state || item.updated.Format(time.RFC3339) != tc.updated {
				t.Errorf("item state/time = %q %s, want %q %s", item.state, item.updated.Format(time.RFC3339), tc.state, tc.updated)
			}
		})
	}
	item, ok := watchItem("Series", seriesEntry{Work: card("unpositioned", "2026-10", "")}, 90, now, testSiteURL)
	if !ok || item.title != "Series: unpositioned" {
		t.Errorf("unpositioned title = %q, keep %v", item.title, ok)
	}
}

// TestReleaseDatePrecisionMirrorsTheSite pins the Go half of the hand-mirrored
// twin in site/src/lib/dates.ts against the SAME cases site/src/lib/dates.test.ts
// pins the TS half against. A reader comparing their /watching list with this
// feed sees two renderings of one catalogue value, so "is it still ahead" and
// "how does it read" must answer identically on both sides - and neither may
// invent precision the catalogue did not state.
func TestReleaseDatePrecisionMirrorsTheSite(t *testing.T) {
	// dates.test.ts's `today`.
	now := time.Date(2026, 9, 21, 15, 0, 0, 0, time.UTC)
	for _, tc := range []struct {
		value  string
		future bool
		reads  string
	}{
		{"2026-09-22", true, "22 Sep 2026"},
		{"2026-09-21", false, "21 Sep 2026"}, // out today: available
		{"2026-09-20", false, "20 Sep 2026"},
		{"2026-10", true, "Oct 2026"}, // a month, never a made-up day
		{"2026-09", false, "Sep 2026"},
		{"2026-08", false, "Aug 2026"},
		// The case that decides the rule: widening "2026" to 1 January would
		// call a book published in March a preorder for the rest of the year.
		{"2026", false, "2026"},
		{"2027", true, "2027"},
		{"2025", false, "2025"},
		{"2026-01-05", false, "5 Jan 2026"}, // no leading zero on a day
	} {
		t.Run(tc.value, func(t *testing.T) {
			parsed, ok := parseReleaseDate(tc.value)
			if !ok {
				t.Fatalf("parseReleaseDate(%q) rejected a stated value", tc.value)
			}
			if got := releaseIsFuture(tc.value, now); got != tc.future {
				t.Errorf("releaseIsFuture(%q) = %v, want %v", tc.value, got, tc.future)
			}
			if got := formatReleaseDate(tc.value, parsed); got != tc.reads {
				t.Errorf("formatReleaseDate(%q) = %q, want %q", tc.value, got, tc.reads)
			}
		})
	}
	// An unparseable value is never a preorder on either side; here it never
	// becomes an item at all, because Atom needs a timestamp for it.
	for _, bad := range []string{"", "next spring", "2026-10-20T00:00:00Z"} {
		if _, ok := parseReleaseDate(bad); ok {
			t.Errorf("parseReleaseDate(%q) accepted an unparseable value", bad)
		}
		if releaseIsFuture(bad, now) {
			t.Errorf("releaseIsFuture(%q) called an unparseable value a preorder", bad)
		}
	}
}

func TestWatchFeedReportsUnknownAndResolvesRetiredSeries(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	_, body := watchFeedResponse(t, ts, "/api/v1/watch/feed.json?s=stormlight-archive,missing-series")
	var feed jsonFeed
	if err := json.Unmarshal(body, &feed); err != nil {
		t.Fatal(err)
	}
	if feed.Description != "The Stormlight Archive. 1 slug not found: missing-series" {
		t.Errorf("description = %q", feed.Description)
	}
	if len(feed.Items) != 3 {
		t.Fatalf("items = %d, want 3", len(feed.Items))
	}
	if !strings.HasPrefix(feed.Items[0].URL, testSiteURL+"/works/") {
		t.Errorf("work URL = %q", feed.Items[0].URL)
	}
}

// An empty feed dates itself by the DAY, not the instant: the ETag is
// day-granular, so a body that moved with the second would put two different
// representations under one validator.
func TestEmptyWatchFeedUsesTheDayAsUpdated(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	_, body := watchFeedResponse(t, ts, "/api/v1/watch/feed.atom?s=missing-series")
	if !strings.Contains(string(body), "<updated>"+dayStart(watchFeedNow).Format(time.RFC3339)+"</updated>") {
		t.Errorf("empty feed does not use the day start for updated:\n%s", body)
	}
	if strings.Contains(string(body), "<entry>") {
		t.Errorf("empty feed contains an entry:\n%s", body)
	}
}

func TestWatchFeedRejectsInvalidParameters(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	tooMany := strings.TrimSuffix(strings.Repeat("the-stormlight-archive,", maxWatchSeries+1), ",")
	for _, path := range []string{
		"/api/v1/watch/feed.json",
		"/api/v1/watch/feed.json?s=z:not!base64",
		"/api/v1/watch/feed.json?s=z:anVuaw",
		"/api/v1/watch/feed.json?s=not_a_slug",
		"/api/v1/watch/feed.json?s=the-stormlight-archive&window=0",
		"/api/v1/watch/feed.json?s=the-stormlight-archive&window=366",
		"/api/v1/watch/feed.json?s=the-stormlight-archive&window=nope",
		"/api/v1/watch/feed.json?s=" + url.QueryEscape(tooMany),
		"/api/v1/watch/releases.ics",
		"/api/v1/watch/releases.ics?s=the-stormlight-archive&window=0",
	} {
		resp, body := watchFeedResponse(t, ts, path)
		if resp.StatusCode != http.StatusBadRequest {
			t.Errorf("GET %s status = %d, want 400; body %s", path, resp.StatusCode, body)
		}
		var out map[string]string
		if err := json.Unmarshal(body, &out); err != nil || out["error"] == "" {
			t.Errorf("GET %s body = %s, want {error}", path, body)
		}
	}
}

func TestWatchFeedETagAnd304(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	path := "/api/v1/watch/feed.atom?s=the-stormlight-archive"
	resp, _ := watchFeedResponse(t, ts, path)
	etag := resp.Header.Get("ETag")
	if etag == "" {
		t.Fatal("feed has no ETag")
	}
	req, err := http.NewRequest(http.MethodGet, ts.URL+path, nil)
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("If-None-Match", etag)
	conditional, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = conditional.Body.Close() }()
	if conditional.StatusCode != http.StatusNotModified {
		t.Errorf("conditional status = %d, want 304", conditional.StatusCode)
	}
	if conditional.Header.Get("Cache-Control") != watchFeedMaxAge {
		t.Errorf("304 Cache-Control = %q", conditional.Header.Get("Cache-Control"))
	}

	other, _ := watchFeedResponse(t, ts, path+"&window=30")
	if other.Header.Get("ETag") == etag {
		t.Errorf("raw window parameter did not change ETag %q", etag)
	}
	jsonResp, _ := watchFeedResponse(t, ts, strings.Replace(path, ".atom", ".json", 1))
	if jsonResp.Header.Get("ETag") == etag {
		t.Errorf("Atom and JSON representations share ETag %q", etag)
	}

	// The calendar is a third representation of the same feed, and the path is
	// a component of the validator, so it gets one of its own - and answers a
	// conditional GET on it.
	icsPath := strings.Replace(path, "feed.atom", "releases.ics", 1)
	icsResp, _ := watchFeedResponse(t, ts, icsPath)
	icsETag := icsResp.Header.Get("ETag")
	if icsETag == "" || icsETag == etag {
		t.Errorf("calendar ETag = %q, Atom ETag %q", icsETag, etag)
	}
	icsReq, err := http.NewRequest(http.MethodGet, ts.URL+icsPath, nil)
	if err != nil {
		t.Fatal(err)
	}
	icsReq.Header.Set("If-None-Match", icsETag)
	icsConditional, err := http.DefaultClient.Do(icsReq)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = icsConditional.Body.Close() }()
	if icsConditional.StatusCode != http.StatusNotModified {
		t.Errorf("conditional calendar status = %d, want 304", icsConditional.StatusCode)
	}
}

// TestWatchFeedETagMovesWithTheDay covers the one input to this body that no
// other cached surface has: the clock. The window is a rolling cutoff and a
// preorder becomes a release on a date, so a validator that named only the
// artifact would let a reader's conditional GET 304-renew yesterday's feed for
// as long as no new data release happened to be cut - losing exactly the news
// the feed exists to carry.
func TestWatchFeedETagMovesWithTheDay(t *testing.T) {
	cat := watchFeedCatalog()
	morning := time.Date(2026, 10, 20, 8, 0, 0, 0, time.UTC)
	srv, err := New(Config{
		DBPath:    buildFixtureDB(t, cat),
		SiteURL:   testSiteURL,
		swapGrace: time.Minute,
		now:       func() time.Time { return morning },
	})
	if err != nil {
		t.Fatal(err)
	}
	snap := srv.current()
	path := "/api/v1/watch/feed.atom"
	same := watchFeedETag(snap, testSiteURL, path, "the-stormlight-archive", "", morning.Add(9*time.Hour))
	first := watchFeedETag(snap, testSiteURL, path, "the-stormlight-archive", "", morning)
	if same != first {
		t.Errorf("ETag changed within one day: %q then %q", first, same)
	}
	next := watchFeedETag(snap, testSiteURL, path, "the-stormlight-archive", "", morning.AddDate(0, 0, 1))
	if next == first {
		t.Errorf("ETag %q did not move with the day", first)
	}
}

func TestWatchFeedCapsItemsAfterOrdering(t *testing.T) {
	author := &model.Person{ID: "author", Name: "Author", License: "CC0-1.0"}
	series := &model.Series{ID: "long-series", Name: "Long Series", License: "CC0-1.0"}
	cat := &model.Catalog{People: []*model.Person{author}, Series: []*model.Series{series}}
	for i := 1; i <= maxWatchFeedItems+5; i++ {
		id := "work-" + strconv.Itoa(i)
		cat.Works = append(cat.Works, &model.Work{
			ID: id, Title: "Work " + strconv.Itoa(i), Authors: []string{author.ID}, Language: "en", License: "CC0-1.0",
			Recordings: []*model.Recording{{
				ID: "recording", Work: id, Language: "en", ReleaseDate: "2027-01-01", License: "CC0-1.0",
			}},
		})
		series.Works = append(series.Works, model.SeriesWork{Work: id, Position: strconv.Itoa(i)})
	}
	_, ts := newWatchFeedServer(t, cat)
	_, body := watchFeedResponse(t, ts, "/api/v1/watch/feed.json?s=long-series")
	var feed jsonFeed
	if err := json.Unmarshal(body, &feed); err != nil {
		t.Fatal(err)
	}
	if len(feed.Items) != maxWatchFeedItems {
		t.Fatalf("items = %d, want %d", len(feed.Items), maxWatchFeedItems)
	}
	if !strings.Contains(feed.Items[0].Title, "#1:") || !strings.Contains(feed.Items[len(feed.Items)-1].Title, "#200:") {
		t.Errorf("cap applied before position ordering: first %q, last %q", feed.Items[0].Title, feed.Items[len(feed.Items)-1].Title)
	}
}

func TestWatchFeedsRequireSnapshot(t *testing.T) {
	srv := &Server{cfg: Config{SiteURL: testSiteURL, now: time.Now}}
	srv.mux = srv.buildMux()
	for _, path := range []string{
		"/api/v1/watch/feed.json?s=series",
		"/api/v1/watch/feed.atom?s=series",
		"/api/v1/watch/releases.ics?s=series",
	} {
		rec := httptest.NewRecorder()
		req := httptest.NewRequest(http.MethodGet, path, nil)
		srv.Handler().ServeHTTP(rec, req)
		if rec.Code != http.StatusServiceUnavailable {
			t.Errorf("GET %s status = %d, want 503", path, rec.Code)
		}
	}
}

// A calendar event needs a date, so a work the catalogue holds no usable
// release date for is carried by the Atom and JSON feeds and omitted here
// rather than placed on the day the catalogue learned of it.
func TestICalendarSkipsUndatedItems(t *testing.T) {
	feed := watchFeed{
		title:   watchFeedTitle,
		id:      "tag",
		self:    testSiteURL + "/api/v1/watch/releases.ics?s=series",
		updated: watchFeedNow,
		items: []watchFeedItem{
			{
				id: watchTagPrefix + "work/dated/released", title: "Series #1: Dated",
				state: "released", summary: "Released 20 Oct 2026", link: testSiteURL + "/works/dated",
				updated: time.Date(2026, 10, 20, 0, 0, 0, 0, time.UTC),
				release: time.Date(2026, 10, 20, 0, 0, 0, 0, time.UTC),
			},
			{
				id: watchTagPrefix + "work/undated/released", title: "Series #2: Undated",
				state: "date unknown", summary: "Added to the catalogue, release date unknown",
				link:    testSiteURL + "/works/undated",
				updated: time.Date(2026, 10, 19, 12, 0, 0, 0, time.UTC),
			},
		},
	}
	body, err := renderICalendar(feed)
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)
	if n := strings.Count(got, "BEGIN:VEVENT"); n != 1 {
		t.Errorf("VEVENT count = %d, want 1:\n%s", n, got)
	}
	if strings.Contains(got, "undated") || strings.Contains(got, "date unknown") {
		t.Errorf("undated item reached the calendar:\n%s", got)
	}
}

// A stated precision is honoured rather than invented: the event lands on the
// first day of the period the catalogue names, and the description says which
// period that was. Built through watchItem so the precision path is the real
// one and not a literal restating what it should produce.
func TestICalendarPrecisionUsesFirstDay(t *testing.T) {
	now := time.Date(2026, 9, 21, 15, 0, 0, 0, time.UTC)
	for _, tc := range []struct {
		release string
		start   string
		reads   string
	}{
		{"2026", "20260101", "2026"},
		{"2026-10", "20261001", "Oct 2026"},
		{"2026-10-20", "20261020", "20 Oct 2026"},
	} {
		t.Run(tc.release, func(t *testing.T) {
			card := &workCard{ID: "work", Title: "Work", ReleaseDate: tc.release}
			item, ok := watchItem("Series", seriesEntry{Position: "1", Work: card}, maxWatchWindow, now, testSiteURL)
			if !ok {
				t.Fatalf("watchItem dropped %q", tc.release)
			}
			body, err := renderICalendar(watchFeed{title: watchFeedTitle, items: []watchFeedItem{item}})
			if err != nil {
				t.Fatal(err)
			}
			got := string(body)
			if !strings.Contains(got, "DTSTART;VALUE=DATE:"+tc.start+"\r\n") {
				t.Errorf("DTSTART for %q is not %s:\n%s", tc.release, tc.start, got)
			}
			if !strings.Contains(got, tc.reads) {
				t.Errorf("DESCRIPTION for %q does not state %q:\n%s", tc.release, tc.reads, got)
			}
		})
	}
}

func TestICSFoldAndEscape(t *testing.T) {
	if got, want := icsText("a,b;c\\d\nx"), `a\,b\;c\\d\nx`; got != want {
		t.Errorf("icsText = %q, want %q", got, want)
	}

	long := "SUMMARY:" + strings.Repeat("a", 200)
	folded := icsFold(long)
	physical := strings.Split(folded, "\r\n")
	if len(physical) < 3 {
		t.Fatalf("a 200-octet line folded into %d physical lines", len(physical))
	}
	unfolded := physical[0]
	for i, line := range physical {
		if len(line) > icsLineOctets {
			t.Errorf("physical line %d is %d octets", i, len(line))
		}
		if i == 0 {
			continue
		}
		if !strings.HasPrefix(line, " ") {
			t.Errorf("continuation line %d does not start with a space: %q", i, line)
		}
		unfolded += line[1:]
	}
	if unfolded != long {
		t.Errorf("unfolded = %q, want %q", unfolded, long)
	}

	// The limit is in OCTETS, so a run of multi-byte runes is where a naive cut
	// would split one and hand the reader an undecodable calendar.
	wide := icsFold("SUMMARY:" + strings.Repeat("\u00e9\u00fc\u4e16", 40))
	for i, line := range strings.Split(wide, "\r\n") {
		if !utf8.ValidString(line) {
			t.Errorf("physical line %d split a rune: %q", i, line)
		}
		if len(line) > icsLineOctets {
			t.Errorf("physical line %d is %d octets", i, len(line))
		}
	}

	// Every line break in a rendered document is a CRLF, folds included.
	body, err := renderICalendar(watchFeed{
		title: watchFeedTitle, subtitle: "A Series",
		items: []watchFeedItem{{
			id: watchTagPrefix + "work/w/released", title: strings.Repeat("Long Title ", 20),
			state: "released", summary: "Released 20 Oct 2026", link: testSiteURL + "/works/w",
			updated: time.Date(2026, 10, 20, 0, 0, 0, 0, time.UTC),
			release: time.Date(2026, 10, 20, 0, 0, 0, 0, time.UTC),
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	for i, b := range body {
		if b == '\n' && (i == 0 || body[i-1] != '\r') {
			t.Fatalf("byte %d is a bare LF:\n%q", i, body)
		}
	}
	if !strings.HasSuffix(string(body), "END:VCALENDAR\r\n") {
		t.Errorf("document does not end with a CRLF-terminated END:VCALENDAR:\n%q", body)
	}
}

func TestICalendarIsDeterministic(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	path := "/api/v1/watch/releases.ics?s=the-stormlight-archive"
	_, first := watchFeedResponse(t, ts, path)
	_, second := watchFeedResponse(t, ts, path)
	if string(first) != string(second) {
		t.Errorf("two renders differ:\n%s\n---\n%s", first, second)
	}
}

// The cap belongs to each REPRESENTATION, after its own filter. The calendar
// leaves undated works out, so a cap taken over the shared list would let them
// spend calendar slots and push the one real release out of the .ics while
// Atom and JSON still carried it.
func TestICalendarCapsAfterDroppingUndated(t *testing.T) {
	feed := watchFeed{
		title:     watchFeedTitle,
		generated: dayStart(watchFeedNow),
	}
	for i := 0; i <= maxWatchFeedItems; i++ {
		id := "undated-" + strconv.Itoa(i)
		feed.items = append(feed.items, watchFeedItem{
			id: watchTagPrefix + "work/" + id + "/released", title: "Undated " + id,
			state: "date unknown", summary: "Added to the catalogue, release date unknown",
			link:    testSiteURL + "/works/" + id,
			updated: time.Date(2026, 10, 19, 12, 0, 0, 0, time.UTC),
		})
	}
	feed.items = append(feed.items, watchFeedItem{
		id: watchTagPrefix + "work/dated/released", title: "The Dated One",
		state: "released", summary: "Released 20 Oct 2026", link: testSiteURL + "/works/dated",
		updated: time.Date(2026, 10, 20, 0, 0, 0, 0, time.UTC),
		release: time.Date(2026, 10, 20, 0, 0, 0, 0, time.UTC),
	})

	body, err := renderICalendar(feed)
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)
	if n := strings.Count(got, "BEGIN:VEVENT"); n != 1 {
		t.Errorf("VEVENT count = %d, want 1", n)
	}
	if !strings.Contains(got, "The Dated One") {
		t.Errorf("the one dated release fell out of the calendar:\n%s", got)
	}
}

// DTSTAMP says when the DOCUMENT was composed, so a preorder's future release
// date never stamps it - and it is day-granular, matching the feed's ETag.
func TestICalendarStampsTheGenerationDay(t *testing.T) {
	_, ts := newWatchFeedServer(t, watchFeedCatalog())
	_, body := watchFeedResponse(t, ts, "/api/v1/watch/releases.ics?s=the-stormlight-archive")
	want := "DTSTAMP:" + dayStart(watchFeedNow).Format("20060102T150405Z")
	stamps := strings.Count(string(body), "DTSTAMP:")
	if stamps == 0 {
		t.Fatalf("no VEVENT in the calendar:\n%s", body)
	}
	if got := strings.Count(string(body), want); got != stamps {
		t.Errorf("%d of %d DTSTAMP lines are %q:\n%s", got, stamps, want, body)
	}
}

// A work in two watched series is one book, so it is one feed item: two would
// be two rows in a reader and, since the item id is also the calendar UID, two
// events on one day.
func TestWatchFeedEmitsEachWorkOnce(t *testing.T) {
	cat := watchFeedCatalog()
	cat.Series = append(cat.Series, &model.Series{
		ID: "stormlight-companion", Name: "Stormlight Companion", License: "CC0-1.0",
		Works: []model.SeriesWork{{Work: "the-way-of-kings", Position: "1"}},
	})
	_, ts := newWatchFeedServer(t, cat)
	_, body := watchFeedResponse(t, ts,
		"/api/v1/watch/feed.json?s=the-stormlight-archive,stormlight-companion")
	var feed jsonFeed
	if err := json.Unmarshal(body, &feed); err != nil {
		t.Fatal(err)
	}
	seen := map[string]int{}
	for _, item := range feed.Items {
		seen[item.URL]++
	}
	shared := testSiteURL + "/works/the-way-of-kings"
	if seen[shared] != 1 {
		t.Errorf("the shared work appears %d times, want 1:\n%s", seen[shared], body)
	}
	// FIRST series in request order wins, so the item still names it.
	for _, item := range feed.Items {
		if item.URL == shared && !strings.HasPrefix(item.Title, "The Stormlight Archive") {
			t.Errorf("shared work kept the second series' title %q", item.Title)
		}
	}
}

// Invalid UTF-8 backs the rune-boundary break off all the way to the start of
// the segment, and a zero-width segment never advances: the fold used to loop
// forever on one. It cuts at the limit instead.
func TestICSFoldSurvivesInvalidUTF8(t *testing.T) {
	done := make(chan string, 1)
	go func() { done <- icsFold(strings.Repeat("\x80", 100)) }()
	var folded string
	select {
	case folded = <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("icsFold did not terminate on invalid UTF-8")
	}
	var joined string
	for i, line := range strings.Split(folded, "\r\n") {
		if len(line) > icsLineOctets {
			t.Errorf("physical line %d is %d octets, want <= %d", i, len(line), icsLineOctets)
		}
		if i == 0 {
			joined = line
			continue
		}
		if !strings.HasPrefix(line, " ") {
			t.Errorf("continuation line %d does not start with a space: %q", i, line)
		}
		joined += line[1:]
	}
	if joined != strings.Repeat("\x80", 100) {
		t.Errorf("unfolding lost bytes: %d of 100", len(joined))
	}
}
